### PR TITLE
Use Parasail from PyPI

### PR DESCRIPTION
**Pull request by jvkersch**
Instead of building Parasail directly, or relying on it via an EDM egg, use the version of Parasail that is available from PyPI.

~Draft status until we can check that the wheels thus built do the job.~

Still to do:
- [x] Update description
- [x] Check built wheels
- [x] Make Docker image rely on generic Python

_Updated description (2022/09/13)_: This PR uses the version of the Parasail shared library that is shipped with the current version of the [parasail-python](https://pypi.org/project/parasail/) package on PyPI. In this way, we can avoid using (1) a specially crafted EDM egg for Parasail, or (2) building Parasail from source and then shipping the shared object file with our wheels. This makes deployment much easier, since we can rely on pip throughout (without the need for special CI scripts, etc).

Implementation notes: 

1. The vpsearch Python extension uses the Parasail library (i.e. the headers and the shared object files) directly, and doesn't use the Python interface that the parasail-python package also provides. That poses a challenge when it comes to linking and loading Parasail, since those shared object files are found somewhere deep inside `site-packages` and their location is not really known at load time. What we can do instead is (a) not link against Parasail during building, and then (b) load the library from within Python when vpsearch is called. There is a small piece of code in `__init.py__` to this effect. This works well on Linux and macOS, but would not work on Windows (which we don't support).  

3. Now that we pull Parasail from PyPI, there is always the risk that we end up with a different ABI than what we built against. Parasail doesn't change very quickly, so this is not likely to be much of an issue, but to avoid it anyway I pinned the version of Parasail that is used. I can't see many cases where there would be a package with another, conflicting dependency on Parasail, so I think pinning is OK.

### CODE REVIEW

**Comment by jvkersch** [comment]
Having written the above description, I wonder if there is some rpath trickery that would achieve the same result (bake into the vpsearch extension where to look for Parasail) as what we do during runtime. I don't know how to do this in a platform-independent way, but I'll have another look.

**Comment by jvkersch** [comment]
I looked into setting `rpath` to a relative location to find Parasail, but I am unable to do this in a way that works both locally (compiling from source) and via wheels (when the wheels are e.g. built in a VM and installed somewhere else). I would suggest that we go ahead with the current approach, which works on Linux and macOS, and revisit this if needed.

@stevenjkern Would you mind giving this a review? Thanks.

**Comment by jvkersch** [comment]
@stevenjkern Did you have a moment to look into this? Once this is in, I'll wrap up the other tasks for the JOSS review.

**Review by stevenjkern — APPROVED** [review]
Looks okay to me! 👍🏻

**Pull request merged**
