### PR TITLE
DEV: Move to Python 3.8 for base environment

### PR DESCRIPTION
**Pull request by jvkersch**
Updates the provided bundles to use Python 3.8. ﻿

### CODE REVIEW

**Comment by jvkersch** [comment]
@stevenjkern Would you have a moment to review this if you get a chance?

**Comment by stevenjkern** [comment]
LGTM. Can you also remove the old `rh6` `cp36` bundle as well?

**Review by stevenjkern — APPROVED** [review]

**Comment by jvkersch** [comment]
> LGTM. Can you also remove the old rh6 cp36 bundle as well?

Thanks @stevenjkern! What rh6 cp36 do you mean specifically? I only see the cp38 bundles...

**Comment by jvkersch** [comment]
@stevenjkern Would you mind using your superpowers to merge this? The tests pass but GitHub expects the results from the 3.6 run. I expect this will work fine once it's in master.

**Comment by stevenjkern** [comment]
> Thanks @stevenjkern! What rh6 cp36 do you mean specifically? I only see the cp38 bundles...

Oops! It wasn't showing up as deleted in the diff on my phone. All good!

**Comment by stevenjkern** [comment]
> Would you mind using your superpowers to merge this? The tests pass but GitHub expects the results from the 3.6 run. I expect this will work fine once it's in master.

Unfortunately, I have no superpowers for this repo. Maybe @rkern does? If not, we can find whoever does and make this happen.

**Comment by mdickinson** [comment]
I can superpower.

**Pull request merged**
